name: build cmake

on:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cmake

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Login to 

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build CMake Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./cmake
          file: ./cmake/Dockerfile
          push: true
          tags: ghcr.io/anothersimplecoder/cmake:latest